### ISSUE TITLE
Link opened in the same tab

### ISSUE THREAD

**Issue by kmb46** [namishkhanna/newtab#1]
Hi there,

I tried the demo, it opens the link in the same tab :disappointed:

P.S. I'm using Brave browser

**Comment by kmb46** [comment]
P.S. It doesn't work in GitHub Markdown (i.e. in readme.md file)

**Comment by namishkhanna** [comment]
@kmb46 I tried it on Brave Browser and it worked fine for me

![Before Click](https://user-images.githubusercontent.com/38690317/109498416-6f503d00-7ab9-11eb-9ac0-61939e52ce32.png)

<br>

![After Click](https://user-images.githubusercontent.com/38690317/109498413-6e1f1000-7ab9-11eb-91fb-0e0021cb5991.png)

Try Clearing your Browser Cache.

**Comment by kmb46** [comment]
@namishkhanna I'm talking about using it in readme.md because you said in an answer to the following issue: https://github.com/mojombo/github-flavored-markdown/issues/28#issuecomment-787728269_

> @AliMD @mojombo Resolved the Issue
> 
> **Try This:** https://namishkhanna.github.io/newtab/?url=http://test.com
> 
> **For Reference:** https://github.com/namishkhanna/newtab

And it doesn't work for fixing that issue like you said.

**Comment by namishkhanna** [comment]
@kmb46 I have also added same type of link in my readme.md please refer to that as it was working fine.

If you find any problem again then please include either screenshot or video of the error.

**Comment by kmb46** [comment]
@namishkhanna the issue is not about opening URL in new tab in GitHub pages, there is even a simple solution for this using markdown, like what was said in https://stackoverflow.com/a/63546509

The problem is about using it directly in GitHub repositories (readme.md files) to open links in new tabs

![Screenshot from 2021-03-01 14-02-55](https://user-images.githubusercontent.com/12597667/109501313-b88f9500-7a97-11eb-8cdc-23955a120f1a.png)
![Screenshot from 2021-03-01 14-02-58](https://user-images.githubusercontent.com/12597667/109501353-c3e2c080-7a97-11eb-9f2f-5ce3cb2f5aec.png)
